#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";

import {
  canonicalStringify,
  compileDesignSystem,
  designContextGenerator,
  generateDesignContext,
  readDesignSystemDefinition,
} from "./index.mjs";

async function main(args) {
  if (
    args.length === 4 &&
    args[0] === "design-context" &&
    args[2] === "--out-dir"
  ) {
    await writeDesignContext(args[1], args[3]);
    return;
  }
  if (args.length !== 4 || args[0] !== "compile" || args[2] !== "--out") {
    throw new Error(
      "usage: ansldes-compile <compile DEFINITION --out BUNDLE|design-context DEFINITION --out-dir DIRECTORY>",
    );
  }
  const [, input, , output] = args;
  const definition = await readDesignSystemDefinition(input);
  const bundle = compileDesignSystem(definition);
  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, canonicalStringify(bundle), "utf8");
  process.stdout.write(
    `compiled ${bundle.definition.id}@${bundle.definition.version} ${bundle.fingerprintSha256}\n`,
  );
}

async function writeDesignContext(input, outputDirectory) {
  const definition = await readDesignSystemDefinition(input);
  const context = generateDesignContext(definition);
  const markdownPath = path.join(outputDirectory, "DESIGN.md");
  const sidecarPath = path.join(outputDirectory, ".impeccable", "design.json");
  await assertGeneratedOrMissing(
    markdownPath,
    "Generated by ansldes-design-context@",
  );
  await assertGeneratedOrMissing(
    sidecarPath,
    `"id": "${designContextGenerator.id}"`,
  );
  await mkdir(path.dirname(sidecarPath), { recursive: true });
  await writeFile(markdownPath, context.designMarkdown, "utf8");
  await writeFile(sidecarPath, canonicalStringify(context.sidecar), "utf8");
  process.stdout.write(
    `generated design context ${context.sidecar.source.contractSha256}\n`,
  );
}

async function assertGeneratedOrMissing(output, marker) {
  const existing = await readFile(output, "utf8").catch(() => null);
  if (existing !== null && !existing.includes(marker)) {
    throw new Error(
      `refusing to overwrite non-generated design context ${output}`,
    );
  }
}

main(process.argv.slice(2)).catch((error) => {
  process.stderr.write(`${error.message}\n`);
  process.exitCode = 1;
});
