version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  modules-download-mode: readonly
  tests: true

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint
    - exhaustive
    - gocritic
    - gosec
    - misspell
    - nilerr
    - nolintlint
    - revive
    - unconvert
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
